repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.6
  hooks:
  - id: clang-format
    types_or: [c]
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
    - id: black
      args: [--config, pyproject.toml]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    - id: ruff
      args: [--fix]
