name: pytest

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install meson
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build
      - name: Install C dependencies
        run: |
          sudo apt-get install -y libglib2.0-dev libsoup-3.0-dev libnftables-dev libsqlite3-dev libjansson-dev
      - name: Install Python dependencies
        run: python -m pip install -r tests/requirements-test.txt
      - name: Run tests
        run: PYTEST_ADDOPTS="-vv --tb=short" make test
