name: pytest

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install meson
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build
      - name: Install dependencies
        run: python -m pip install pytest
        run: |
          sudo apt-get install -y libglib2.0-dev libsoup2.4-dev libnftables-dev libsqlite3-dev libjansson-dev
      - name: Run tests
        run: make test
